<?php return array (
  'logo' => NULL,
  'title_ru' => '15 пазлов',
  'title_eng' => '15 puzzles',
  'h1_ru' => 'Протоколы лечения рака  целостной медицины',
  'h1_eng' => 'Cancer reversal protocols  of holistic medicine',
  'description_ru' => '<h2 class="main__left-title" style="margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; background-color: transparent; color: rgb(54, 68, 88); font-weight: 600; font-family: &quot;Open Sans&quot;, sans-serif;"><span style="background-color: transparent; color: rgb(89, 89, 106); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-weight: 600; text-decoration-line: none; display: inline !important; float: none;">Есть 15 известных «пазлов» головоломки рака, которые участвуют в известных протоколах лечения естественного рака.</span><br></h2><div class="main__left-text" style="margin: 0px 0px 30px; padding: 0px; border: 0px; outline: 0px; background-color: transparent; color: rgb(89, 89, 106); font-size: 16px; font-family: &quot;Open Sans&quot;, sans-serif;"><div class="main__left-text" style="margin: 0px 0px 30px; padding: 0px; border: 0px; outline: 0px; background-color: transparent;">Этот веб-сайт является вашей исследовательской базой, чтобы узнать, как именно ваше тело «запуталось» в процессе развития рака, и попытаться разработать собственный план обращения процесса канцерогенеза, основанный на лучших известных методах лечения натуропатического рака. Этот веб-сайт является вашей исследовательской базой, чтобы узнать, как именно ваше тело «запуталось» в процессе развития рака, и попытаться разработать собственный план обращения процесса канцерогенеза, основанный на лучших известных методах лечения натуропатического рака.</div></div>',
  'description_eng' => '<div class="main__left-subtitle" style="margin: 0px 0px 30px; padding: 0px; border: 0px; outline: 0px; background-color: transparent; color: rgb(89, 89, 106); font-size: 16px; font-weight: 600; font-family: &quot;Open Sans&quot;, sans-serif;">There are 15 known "pieces" of the cancer puzzle that are involved in known natural cancer treatment protocols.</div><div class="main__left-text" style="margin: 0px 0px 30px; padding: 0px; border: 0px; outline: 0px; background-color: transparent; color: rgb(89, 89, 106); font-size: 16px; font-family: &quot;Open Sans&quot;, sans-serif;"><div class="main__left-text" style="margin: 0px 0px 30px; padding: 0px; border: 0px; outline: 0px; background-color: transparent;">This web site is your research base to find out how exactly your body got "confused" in the process of developing the cancer and try develop your own plan of reversing the cancerogenesis process based on the best known practices in naturopathic cancer treatment.<br style="margin: 0px; padding: 0px; border: 0px; outline: 0px; background-color: transparent;"><br style="margin: 0px; padding: 0px; border: 0px; outline: 0px; background-color: transparent;">This web site is your research base to find out how exactly your body got "confused" in the process of developing the cancer and try develop your own plan of reversing the cancerogenesis process based on the best known practices in naturopathic cancer treatment.</div></div>',
  'puzzles_description_ru' => '<p><span style="color: rgba(89, 89, 106, 0.5); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(237, 243, 247);">На первый взгляд 15 частей ракового процесса могут показаться странными. Но имейте в виду, что свидетельства загадки есть только в 1-2 ходах. Может потребоваться переместить целых 4 или 6 частей, чтобы исправить свое тело, не стесняйтесь исследовать головоломку и разобраться с ней!</span><br data-cke-filler="true"></p>',
  'puzzles_description_eng' => '<p><span style="color: rgba(89, 89, 106, 0.5); font-family: &quot;Open Sans&quot;, sans-serif; background-color: rgb(237, 243, 247);">The 15 pieces of the cancer process may look confusing at a first glance. But keep in mind that there are evidences of&nbsp;</span><completing style="margin: 0px; padding: 0px; border: 0px; outline: 0px; background-color: rgb(237, 243, 247); color: rgba(89, 89, 106, 0.5); font-family: &quot;Open Sans&quot;, sans-serif;">the riddle in 1-2 moves only. It might be necessary to move as much as 4 or 6 pieces to fix your body, feel free to explore the puzzle and sort it out!</completing><br data-cke-filler="true"></p>',
  'link_video' => 'http://techslides.com/demos/sample-videos/small.mp4',
);